version: '3'

services:
  service1:
    build:
      context: ./ms1
    volumes:
      - ./db:/db
    ports:
      - "3001:3001"
  service2:
    build:
      context: ./ms2
    volumes:
      - ./db:/db  
    ports:
      - "3002:3002"
  angular:
    image: angular-nginx-docker
    build:
      context: ./web
    environment:
      NODE_ENV: production
    ports:
      - 80:80 
    depends_on:
      - service1
      - service2